[project]
name = "apply-macro"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "keyboard>=0.13.5",
    "pyautogui>=0.9.54",
    "pywin32>=311",
    "pywinauto>=0.6.9",
]
